### ISSUE TITLE
Question about encoding feature

### ISSUE THREAD

**Issue by fcaride** [SvenTiigi/EUDCCKit#5]
Hello there

I dont understand how the encoding function works, how can i encode a eudcc object in order to get the base45 representation?

Thanks!

**Comment by SvenTiigi** [comment]
Hi @fcaride,

Encoding an `EUDCC` to a Base-45 CBOR  is and will not be supported as this impossible because a valid EU Digital COVID Certificate needs to be signed with a private key from on official authority.

The implementation of the `Encodable` protocol for the `EUDCC` object is currently limited to converting it back to the original JSON format which is the content of the decoded CBOR.
